# Generated by Django 4.1.7 on 2023-04-05 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0006_insurancedetails_verified_medicaldetails_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthscore', models.IntegerField(default=100)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('prem_cost', models.IntegerField(blank=True, null=True)),
                ('pay_pending', models.BooleanField(default=False)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SubRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthscore', models.IntegerField(default=100)),
                ('req_date', models.DateField(auto_now_add=True)),
                ('pending', models.BooleanField(default=True)),
                ('prem_cost', models.IntegerField(blank=True, null=True)),
                ('pat_accept', models.BooleanField(default=False)),
                ('pat_reject', models.BooleanField(default=False)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
