# Generated by Django 4.1.7 on 2023-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='profile',
            field=models.ImageField(default='nothing.img', upload_to='patientprofile/'),
            preserve_default=False,
        ),
    ]
