# Generated by Django 4.1.7 on 2023-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_patientdetails_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='name',
            field=models.CharField(default='testdata', max_length=50),
            preserve_default=False,
        ),
    ]
