# Generated by Django 4.1.7 on 2023-04-05 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0003_remove_patientdetails_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=12)),
                ('alt_telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('insttype', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('SemiPrivate', 'SemiPrivate'), ('Individual', 'Individual')], default='Private', max_length=20)),
                ('medicining', models.CharField(choices=[('Allopathy', 'Allopathy'), ('Homeopathy', 'Homeopathy'), ('Naturopathy', 'Naturopathy'), ('Ayurvedic', 'Ayurvedic')], default='Allopathy', max_length=30)),
                ('establishment', models.DateField()),
                ('reg_no', models.CharField(max_length=100)),
                ('estproof', models.FileField(upload_to='instproof/')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='medicalprofile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=12)),
                ('alt_telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('establishment', models.DateField()),
                ('reg_no', models.CharField(max_length=100)),
                ('estproof', models.FileField(upload_to='instproof/')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='insureprofile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
