# Generated by Django 4.1.7 on 2023-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_medicaldetails_insurancedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetails',
            name='insttype',
            field=models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('SemiPrivate', 'SemiPrivate'), ('Individual', 'Individual')], default='Private', max_length=20),
        ),
    ]
