# Generated by Django 4.1.7 on 2023-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_insurancedetails_insttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetails',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
